server:
  http_listen_port: 9080

positions:
  filename: /run/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/**/*-json.log

    pipeline_stages:
      - docker: {}

      - labels:
          container:
          com_docker_compose_service:
          com_docker_compose_project:

      - labelallow:
          - container
          - com_docker_compose_service
          - com_docker_compose_project
          - job
          - level

      - match:
          selector: '{container=~".+"}'
          stages:
            - json:
                expressions:
                  level: level
                  msg: msg
                  message: message
            - labels:
                level:
